### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hpieroni** [hpieroni/hpieroni.com#1]
- [x] maybe replace icons with `react-icons`
- [ ] improve design and layout
- [ ] use tailwind.css
- [ ] improve about me section
